PR_PAGE = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>市赚率 PR 估值</title>
<style>body{font-family:system-ui,"Microsoft YaHei",sans-serif;background:#f5f7fb;color:#182230;margin:0}.wrap{max-width:1200px;margin:auto;padding:28px}nav[aria-label="监控模式"]{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:24px}nav[aria-label="监控模式"] a{color:#2457a6;text-decoration:none;font-weight:600;border:1px solid #d5deeb;border-radius:999px;padding:6px 12px}.hero,.card{background:#fff;border:1px solid #e1e7f0;border-radius:14px;padding:22px;margin-bottom:18px;box-shadow:0 5px 18px #1f3b5d0d}.hero h1{margin:0 0 8px}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}.metric{font-size:28px;font-weight:700;color:#155eef}.warn{color:#b54708}.bad{color:#b42318}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #edf0f5}th{background:#f8fafc}.pill{padding:4px 9px;border-radius:99px;background:#eef4ff;color:#2457a6;font-size:12px}.empty{padding:24px;text-align:center;color:#667085}@media(max-width:700px){.wrap{padding:16px}table{font-size:13px}}</style></head>
<body><main class="wrap"><nav aria-label="监控模式"><a href="/swing">波段监控</a><a href="/">做T监控</a><a href="/pr" aria-current="page">PR估值</a><a href="/notifications">通知中心</a></nav>
<section class="hero"><h1>市赚率 PR 估值</h1><p class="muted">按ETF跟踪指数计算，优先使用 PE ÷ ROE；缺少ROE时交叉展示 PE² ÷ PB ÷ 100。仅作估值观察，不产生交易指令。</p></section>
<section class="card"><div id="summary" class="grid"><div><div class="muted">状态</div><div class="metric">加载中</div></div></div></section>
<section class="card"><h2>ETF与指数估值</h2><div id="table" class="empty">正在读取估值数据...</div></section>
<section class="card"><h2>口径说明</h2><p class="muted">PR = PE ÷ ROE（ROE按百分数输入）；交叉公式 PR = PE² ÷ PB ÷ 100。PR越低通常表示当前价格相对盈利能力越低，但周期、成长、金融行业不宜机械套用同一阈值。数据日期、来源和异常状态以服务端返回为准。</p></section></main>
<script>
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(v,d=2)=>v==null?'—':Number(v).toFixed(d);
async function load(){const r=await fetch('/api/valuations');if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();const items=d.items||[];const valid=items.filter(x=>x.valuation&&x.valuation.pr_pe_roe!=null);document.querySelector('#summary').innerHTML='<div><div class="muted">指数数量</div><div class="metric">'+items.length+'</div></div><div><div class="muted">已有PR</div><div class="metric">'+valid.length+'</div></div><div><div class="muted">数据状态</div><div class="metric">只读</div></div>';
if(!items.length){document.querySelector('#table').textContent='暂无ETF估值映射数据';return}document.querySelector('#table').innerHTML='<table><thead><tr><th>ETF</th><th>跟踪指数</th><th>PE</th><th>PB</th><th>ROE</th><th>PR(PE/ROE)</th><th>PR(PE/PB)</th><th>日期</th><th>状态</th></tr></thead><tbody>'+items.map(x=>{const v=x.valuation||{};return '<tr><td>'+esc(x.symbol)+' '+esc(x.name)+'</td><td>'+esc(x.index?.code)+' '+esc(x.index?.name)+'</td><td>'+fmt(v.pe_ttm)+'</td><td>'+fmt(v.pb)+'</td><td>'+fmt(v.roe_ttm)+'%</td><td><b>'+fmt(v.pr_pe_roe)+'</b></td><td>'+fmt(v.pr_pe_pb)+'</td><td>'+esc(v.as_of||'—')+'</td><td><span class="pill">'+esc(x.status||'UNKNOWN')+'</span></td></tr>'}).join('')+'</tbody></table>'}
load().catch(e=>{document.querySelector('#table').innerHTML='<div class="empty bad">估值接口暂不可用：'+esc(e.message)+'</div>'});
</script></body></html>'''
